### ISSUE TITLE
Handle limits on parallel API calls

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/geocoding-augmentation#2]
https://github.com/keboola/geocoding-augmentation/blob/master/JobExecutor.php#L185 - nefailovat, ale přidat retry při dosažení limitu na konkurentní API cally - pozor aby se neopakovalo donekonečna, nevím jestli např. Google rozlišuje mezi překročením limitu na počet requestů za sekundu a za den.

Omezit paralelní běh na 10: https://github.com/keboola/geocoding-augmentation/blob/master/JobExecutor.php#L164

**Comment by ujovlado** [comment]
Este pridavam link na Usage Limits:
https://developers.google.com/maps/documentation/geocoding/usage-limits
