### ISSUE TITLE
Openstreetmap  errors

### ISSUE THREAD

**Issue by Halama** [keboola/geocoding-augmentation#9]
https://keboola.zendesk.com/agent/tickets/10359

Diskuze: https://keboolaglobal.slack.com/archives/CBX9MB2NT/p1556032440058300?thread_ts=1556032440.058300

> jakub: It’s weird, maybe there could be a problem that the geocoding library under the hood of our component calls `http` instead of `https` and doesn’t handle the automatic redirect. Please send it to the support for the record. I’ll look on it.

**Comment by JakubMatejka** [comment]
@Halama vypadá ok: https://connection.keboola.com/admin/projects/313/jobs/499340391

**Comment by Halama** [comment]
jj taky jsem zkoušel a prošlo mi to. Řekl jsem jim ať to vyzkouší.

**Comment by Halama** [comment]
Potvrdili že jim to jede 👍
